stages:
  - build
  - deploy

image: gradle:8.10.2-jdk23-alpine

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=true -Dorg.gradle.parallel=true -Dorg.gradle.caching=true"

cache:
  key: "$CI_COMMIT_REF_SLUG"
  paths:
    - .gradle/wrapper
    - .gradle/caches
    - build/libs/

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle
  - apk add --no-cache curl git

build:
  stage: build
  script:
    - gradle --daemon --parallel --build-cache jar
  artifacts:
    paths:
      - build/libs/*.jar

deploy:
  stage: deploy
  script:
    - gradle publish
  only:
    - main